name: Update JS Bundle and Example Report

on:
  schedule:
  # Run on the first day of the month
    - cron:  '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: read

env:
  MIN_PYTHON_VERSION: "3.9"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
        with:
          python-version: ${{ env.MIN_PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Update the JavaScript bundle
        run: |
          make build-js

      - name: Generate the updated reports
        run: |
          make generate-report

      - name: Run NPM unit tests for sanity checks
        run: |
          make test-js

      - name: PR if files were updated
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: Update JS Bundle and example reports
          title: 'Updates JS Bundle and example reports'
          body: This is an automated PR created to update the JS Bundle and the example reports.
