name: Update JS Bundle and Example Report

on:
  schedule:
  # Run on the first day of the month
    - cron:  '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867  # v7.1.6
        with:
          activate-environment: true
      - run: uv sync --frozen

      - name: Update the JavaScript bundle
        run: just build-js
      - name: Generate the updated reports
        run: just generate-report
      - name: Run NPM unit tests for sanity checks
        run: just test-js

      - name: PR if files were updated
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          commit-message: Update JS Bundle and example reports
          title: 'Updates JS Bundle and example reports'
          body: This is an automated PR created to update the JS Bundle and the example reports.
